version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
      - docker build -t nestjs-test .
      - docker tag nestjs-test 152341231368.dkr.ecr.ap-northeast-1.amazonaws.com/nestjs-test:latest
      - cd $CODEBUILD_SRC_DIR
 
artifacts:
  files:
    - imagedefinitions.json
cache:
  paths:
    - './node_modules/**/*'