version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
      - docker build -t nestjs-test .
      - docker tag nestjs-test 152341231368.dkr.ecr.ap-northeast-1.amazonaws.com/nestjs-test:latest
      - cd $CODEBUILD_SRC_DIR
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 152341231368.dkr.ecr.ap-northeast-1.amazonaws.com/nestjs-test:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nestjs-test","imageUri":"%s"}]' 152341231368.dkr.ecr.ap-northeast-1.amazonaws.com/nestjs-test > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
cache:
  paths:
    - './node_modules/**/*'